version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coop-voting-system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha@123
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: coop-voting-system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: